- name: gpt-3-fwd
  model: microsoft/phi-2
  api_base: ${OPENAI_API_BASE}
  temperature: 0.0
  max_tokens: 128

- name: gpt-3-bwd
  model: microsoft/phi-2
  api_base: ${OPENAI_API_BASE}
  temperature: 0.7
  max_tokens: 128

# - name: llama2-fwd
#   model: /data/llama2/70Bf
#   api_key: EMPTY
#   api_base: http://127.0.0.1:8000/v1
#   api_type: null
#   api_version: null
#   max_tokens: 256
#   temperature: 0
